### ISSUE TITLE
I am using this code its giveing me this error 

### ISSUE THREAD

**Issue by ahmadsaadkhan** [chonthu/Fedex#1]
I am using this api its giveing me this error  as i have inserted all the credentials 

Fatal error: Uncaught exception 'Exception' with message 'This method requires a shipper to be set' in C:\xampp\htdocs\solar\bnhl\appsbnhl\libraries\fed\fedex.php:568 Stack trace: #0 C:\xampp\htdocs\solar\bnhl\appsbnhl\libraries\fed\fedex.php(410): Fedex->validate(Array) #1 C:\xampp\htdocs\solar\bnhl\appsbnhl\controllers\shipping.php(46): Fedex->getRates() #2 [internal function]: Shipping->fedex() #3 C:\xampp\htdocs\solar\bnhl\bnhlsys\core\CodeIgniter.php(359): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\solar\index.php(206): require_once('C:\xampp\htdocs...') #5 {main} thrown in C:\xampp\htdocs\solar\bnhl\appsbnhl\libraries\fed\fedex.php on line 568

**Comment by chonthu** [comment]
Sound like you haven't appended the shipper method onto the FedEx object. Please confirm.

Best

-- 

Nithin Meppurathu

**Comment by ahmadsaadkhan** [comment]
Can you specify what i'm doing wrong with some code help?

**Comment by chonthu** [comment]
Show me the code you have so far, and ill show you. Basically $fedex-> setShipper(array( // Contact Information ),  array( // Address Information ) )
